// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TOB.Identity.Infrastructure.Data.Entities;

public partial class Permission
{
    public Permission()
    {
        RolePermissionMappings = new HashSet<RolePermissionMapping>();
    }

    [Key]
    public Guid PermissionId { get; set; }
    [Required]
    [StringLength(200)]
    public string PermissionName { get; set; }
    public bool IsActive { get; set; }
    public Guid? CreatedBy { get; set; }
    public Guid? UpdatedBy { get; set; }
    public DateTime? CreatedDateTime { get; set; }
    public DateTime? UpdatedDateTime { get; set; }
    public int? SortOrder { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<RolePermissionMapping> RolePermissionMappings { get; set; }
}