// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TOB.Identity.Infrastructure.Data.Entities;

public partial class Role
{
    public Role()
    {
        RolePermissionMappings = new HashSet<RolePermissionMapping>();
        UserRoleMappings = new HashSet<UserRoleMapping>();
    }

    [Key]
    public Guid RoleId { get; set; }
    [Required]
    [StringLength(200)]
    public string RoleName { get; set; }
    public int? SortOrder { get; set; }
    public Guid? CreatedBy { get; set; }
    public Guid? UpdatedBy { get; set; }
    public DateTime? CreatedDateTime { get; set; }
    public DateTime? UpdatedDateTime { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolePermissionMapping> RolePermissionMappings { get; set; }
    [InverseProperty("Role")]
    public virtual ICollection<UserRoleMapping> UserRoleMappings { get; set; }
}