// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TOB.Identity.Infrastructure.Data.Entities;

public partial class RolePermissionMapping
{
    [Key]
    public Guid Id { get; set; }
    public Guid RoleId { get; set; }
    public Guid PermissionId { get; set; }
    public Guid? CreatedBy { get; set; }
    public Guid? UpdatedBy { get; set; }
    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }
    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [ForeignKey("PermissionId")]
    [InverseProperty("RolePermissionMappings")]
    public virtual Permission Permission { get; set; }
    [ForeignKey("RoleId")]
    [InverseProperty("RolePermissionMappings")]
    public virtual Role Role { get; set; }
}