// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TOB.Identity.Infrastructure.Data.Entities;

public partial class Tenant
{
    public Tenant()
    {
        Users = new HashSet<User>();
    }

    [Key]
    public Guid TenantId { get; set; }
    [Required]
    [StringLength(200)]
    public string TenantName { get; set; }
    [StringLength(1000)]
    public string LogoUrl { get; set; }
    [StringLength(500)]
    public string TenantWebsite { get; set; }
    [StringLength(200)]
    public string TenantAddress1 { get; set; }
    [StringLength(200)]
    public string TenantAddress2 { get; set; }
    [StringLength(200)]
    public string TenantCity { get; set; }
    [StringLength(20)]
    public string TenantState { get; set; }
    [StringLength(20)]
    public string TenantZip { get; set; }
    [StringLength(15)]
    [Unicode(false)]
    public string TenantPhoneNumber { get; set; }
    [StringLength(15)]
    [Unicode(false)]
    public string TenantFax { get; set; }
    [Required]
    [StringLength(200)]
    public string ContactFirstName { get; set; }
    [Required]
    [StringLength(200)]
    public string ContactLastName { get; set; }
    [StringLength(15)]
    [Unicode(false)]
    public string ContactPhoneNumber { get; set; }
    [Required]
    [StringLength(200)]
    public string ContactEmail { get; set; }
    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }
    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }
    public Guid? UpdatedBy { get; set; }
    public Guid? CreatedBy { get; set; }
    public bool? IsActive { get; set; }

    [InverseProperty("Tenant")]
    public virtual ICollection<User> Users { get; set; }

}